# Generated by Django 5.0.4 on 2024-04-14 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('tipo_estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radiologia_imagen.estudio')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(max_length=500)),
                ('imagen', models.BinaryField()),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radiologia_imagen.cita')),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radiologia_imagen.estudio')),
            ],
        ),
    ]
