# Generated by Django 5.0.1 on 2024-04-19 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radiologia_imagen', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consumible',
        ),
    ]
